# docker-compose.yml
version: '3.8'
services:
  ethereum-node:
    build: ./ethereum-node
    ports:
      - "8545:8545"
  subscription-service:
    build: ./subscriptions-service
    volumes:
      - ./subscriptions-service:/app
    ports:
      - "4001:4001"
  callback-service:
    build: ./callback-service
    volumes:
      - ./callback-service:/app
    ports:
      - "4002:4002"
  gateway:
    build: ./gateway
    volumes:
      - ./gateway:/app
    ports:
      - "4000:4000"
    depends_on:
      - subscription-service
  indexer:
    build: ./indexer
    volumes:
      - ./indexer:/app
    depends_on:
      - ethereum-node
  sample-app:
    build: ./sample-app
    volumes:
      - ./sample-app:/app
    ports:
      - "3001:3001"

  front-end:
    build: ./front-end
    volumes:
      - ./front-end:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - gateway
      - ethereum-node
      - sample-app

